### ISSUE TITLE
Using an alert with multiple columns output results in diff noise

### ISSUE THREAD

**Issue by alonz** [logzio/terraform-provider-logzio#101]
Creating an alert with multiple fields/columns table output, for example
```
output_type = "TABLE"
sub_components {
    ...
    columns {
        field_name = "field1"
        sort = "DESC"
        regex = ".+"
    }
    columns {
        field_name = "field2"
        regex = ".+"
        sort = "DESC"
    }
    columns {
        field_name = "field3"
        regex = ".+"
        sort = "DESC"
    }
  }
```

we must set a sort a value for each of the columns with a value of DESC/ASC otherwise it will result in an error similar to
```
Error: sort type "sub_components.0.columns.1.sort" must be one of [ASC DESC]
```

but the API can only hold sort value for one of the columns setting a null value for the other fields
```
"output": {
    "columns": [
        {
            "fieldName": "field1",
            "regex": ".+",
            "sort": "DESC"
        },
        {
            "fieldName": "field2",
            "regex": ".+",
            "sort": null
        },
        {
            "fieldName": "field3",
            "regex": ".+",
            "sort": null
        }
    ]
```

which in turn causes terraform to keep trying to change these fields back on every run.

**workaround:**
removing the sort fields (for the 2nd & 3rd columns) after the alert is created will allow terraform to match the configuration and it will suggest no further changes, however, if the alert resource is destroyed it can no longer be created without adding the sort fields back

**Comment by mirii1994** [comment]
Hi @alonz , v1.8.2 of the provider should solve this issue.
Can you upgrade your provider version and confirm that this issue was resolved?

**Comment by alonz** [comment]
Yep, after upgrading the provider the issue is solved.
Thanks!
