### ISSUE TITLE
Alert is_enabled field is does not default to true

### ISSUE THREAD

**Issue by alonz** [logzio/terraform-provider-logzio#102]
According to [ the alerts v2 docs](https://github.com/logzio/terraform-provider-logzio/blob/403d30cc2873dfcf927140ac118fc3b4cb71e087/docs/resources/alert_v2.md?plain=1#L55)
> `is_enabled` - (Boolean) True by default

however omitting `is_enabled` from my TF file, results in terraform plan attempting to set it to null 

```
  ~ resource "logzio_alert_v2" "deployment_alerts" {
        id                             = "1954723"
      - is_enabled                     = true -> null
        tags                           = [
            "alert",
            "deployment",
        ]
        # (13 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
which in turn disables the alert
So either the documentation is wrong or it does not work as intended.
Not a big issue just requires always setting `is_enabled = true` to get an active alert.

**Comment by mirii1994** [comment]
Hi @alonz ,
Thanks for reaching out.
We'll work on a fix for it in the next version.

**Comment by mirii1994** [comment]
Hi @alonz , we release v1.10.3 that should resolve this issue.
Can you please confirm that the issue is solved?

**Comment by alonz** [comment]
Thanks !
