### ISSUE TITLE
Alerts tag needs to be order alphabetically

### ISSUE THREAD

**Issue by alonz** [logzio/terraform-provider-logzio#103]
**Steps to reproduce:**
1. Create an alert with multiple tags which are not ordered alphabetically, similar to:
```
resource "logzio_alert_v2" "test" {
  title = "test"
  description = "test"
  is_enabled = false
  tags = ["c", "b", "a"]
```
2. run the terraform plan again, and it will detect diff noise:
```

  # module.olympus.logzio_alert_v2.test will be updated in-place
  ~ resource "logzio_alert_v2" "test" {
        id                             = "1958124"
      ~ tags                           = [
          - "a",
          - "b",
            "c",
          + "b",
          + "a",
        ]
        # (14 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

this is due to the API returning the tags in alphabetical order and not the order entered by terraform 
```
{
		"id": 1958124,
		"updatedAt": "2022-02-23T10:09:45.000Z",
		"createdAt": "2022-02-23T10:09:45.000Z",
		"enabled": false,
		"title": "test",
		"description": "test",
		"tags": [
			"a",
			"b",
			"c"
		],
```

This is obviously a minor issue that can be easily overcome by setting the tags in alphabetical order, if this is the intended behavior it would be beneficial to update the docs accordingly, but a better solution is that the provider to sort the tags.

**Comment by mirii1994** [comment]
Hi @alonz ,
Thank you, we'll work on a fix for our next version.

**Comment by mirii1994** [comment]
Hi @alonz , we release v1.10.3 that should resolve this issue.
Can you please confirm that the issue is solved?

**Comment by alonz** [comment]
Thanks !
