### ISSUE TITLE
Add a folder creation

### ISSUE THREAD

**Issue by afreyermuth98** [logzio/terraform-provider-logzio#157]
Is it possible to bring a folder creation to the provider ?
Indeed we have the dashboard creation but it needs to refer to a folder uid which can be created only manually so we cannot bring all infra as code without this ...
Moreover it seems that the public API is not able to perform a folder creation so we cannot bypass this step and we are forced to do it manually

**Comment by mirii1994** [comment]
Hi @afreyermuth98 thank you for your feedback.
We will work on adding folders to the provider :)

**Comment by 8naama** [comment]
Hey @afreyermuth98!
Grafana folders are available from version 1.14.0:
https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/grafana_folder
