### ISSUE TITLE
Omitting `output_type` for `logzio_alert_v2` displays false-positive changes while planning

### ISSUE THREAD

**Issue by kirill-artamonov-form3** [logzio/terraform-provider-logzio#161]
`output_type` [isn't a required field for `logzio_alert_v2`](https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/alert_v2#optional).
If it's omitted,  created alert gets "JSON" `output_type` set.

All consecutive plans will then report:
<img width="441" alt="Screenshot 2023-05-25 at 11 54 01" src="https://github.com/logzio/terraform-provider-logzio/assets/100574434/f9ffd4c1-3ca2-4bab-af6d-7336d5f77928">
without any effective changes applied

**Comment by mirii1994** [comment]
Hi @kirill-artamonov-form3,
Thank you for reporting this bug.
We'll work on releasing a fix.

**Comment by mirii1994** [comment]
@kirill-artamonov-form3 just a quick update-
`JSON` is the default value for the API, so this is why you encountered this behavior.
In the next release, I'll add `JSON` as a default in the provider as well to match the API's behavior, and you won't have this conflict.
