### ISSUE TITLE
Create a resourse to manage Metrics account

### ISSUE THREAD

**Issue by michelmorin** [logzio/terraform-provider-logzio#167]
Would like to have an official terraform resource to manage our Metrics Account instead of calling the API at https://docs.logz.io/api/#tag/Manage-metrics-account similar to the logzio_subaccount resource.

Also, as a side question.   We also have Tracing Accounts but don't see any API to manage those.   Would like to have automation for those types of accounts as well

**Comment by 8naama** [comment]
Hey @michelmorin!
Metric Accounts are now available in the provider starting from version 1.15.0:
https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/metrics_account
