### ISSUE TITLE
Errors apply on update of resource logzio_metrics_account

### ISSUE THREAD

**Issue by michelmorin** [logzio/terraform-provider-logzio#192]
Getting errors on apply using resource logzio_metrics_account
https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/metrics_account

Reproducible steps.    From an existing metrics account in logzio, import the resource where xxxxx is the metrics account id
terraform import metrics_account xxxxx

This above steps works and verify all the fields are populated in the state of account name, plan uts, authorized_account, account_token

Changing the value of the plant_uts causes errors running with:

Error: All attempts fail:
│ #1: API call UpdateMetricsAccount failed with status code 400, data: {"errorCode":"METRICS_ACCOUNT/SUB_ACCOUNT_NOT_OWNED","message":"Sub account is not found for the owner account (948339). Reason: Account is not found (or not owned): [xxxxxx]","requestId":"172a0d40-1fbc-4b45-8b26-c1604b07537e","parameters":{"accountId":xxxxxx,"reason":"Account is not found (or not owned): [xxxxxx]"}}

The same happens in the UI using https://api-docs.logz.io/docs/logz/update-a-metrics-account when you provide account_name.  When contacting support, this works when account_name is remove and only include plan_uts when updating, but it doesn't work with terraform as I believe all fields are passed

The same error occurs if I create a new Metrics Account using the resource, see example below, which is successful, but if I change the plan_uts from say 100 to 200, I get the same error

example
resource "logzio_metrics_account" "metrics_account" {
  email               = email@example.com
  account_name        = METRICS_ACCOUNT_NAME
  plan_uts            = 100
  authorized_accounts = []
}

**Comment by yotamloe** [comment]
Hey @michelmorin Thanks for reporting this issue, it looks like its an issue with the public API we are investigating.

**Comment by yotamloe** [comment]
@michelmorin There is an issue with this public API endpoint. We are working on it

**Comment by ralongit** [comment]
Hello @michelmorin, we have applied changes to our API. 
Can you please check if the error still occurs?

**Comment by michelmorin** [comment]
@yotamloe I have tested the version 1.16.0 logzio provider and everything worked without error.   Thank you so much

**Comment by yotamloe** [comment]
@michelmorin Thank you for reporting this bug. Closing this issue
