### ISSUE TITLE
Support import/export of Kibana objects

### ISSUE THREAD

**Issue by pengux** [logzio/terraform-provider-logzio#59]
API docs: https://docs.logz.io/api/#operation/exportSavedObjects

**Comment by pengux** [comment]
I'm working on a PR for this issue.

**Comment by yyyogev** [comment]
Hi @pengux 
Thank you for your interest to contribute. The first PR should implement the import/export operations in the [client repo](https://github.com/logzio/logzio_terraform_client). 
Then you can work on your PR for the provider.
Thanks a lot!

**Comment by mirii1994** [comment]
Hi @pengux as of v1.9.0 we support import/export of Kibana Object (#111 ).
Closing this issue.
Feel free to open a new one if you need some help!
