### ISSUE TITLE
Creating multiple alerts results in API call GetAlert failed with status code 404

### ISSUE THREAD

**Issue by sensedata1** [logzio/terraform-provider-logzio#60]
I'm creating around 150 alerts at a time and around half the alerts produce the following error each time:
```
Error: API call GetAlert failed with status code 404, data: "no alert id 1081563 found for account XXXXXX"

  on alerts.tf line 13, in resource "logzio_alert" "mule":
  13: resource "logzio_alert" "mule" {
```

When I run with TRACE I see these warnings which may or may not be related:

```2021/03/02 15:46:26 [WARN] Provider "registry.terraform.io/logzio/logzio" produced an invalid plan for logzio_alert.mule["155"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .filter: planned value cty.StringVal("{\"bool\":{\"must\":[],\"should\":[],\"filter\":[],\"must_not\":[]}}") does not match config value cty.NullVal(cty.String)
```
Running an apply multiple times eventually results in no errors, once the alerts are created they can be updated in situ without issue. 

my resource definition is as follows:
```
resource "logzio_alert" "mule" {
  for_each                       = var.create_logzio_mule_alerts ? var.mule_alerts : {}
  title                          = "${each.value["severity"]}-${local.environment}-${each.key} ${each.value["title"]}"
  query_string                   = <<-EOT
  ${local.query_start}${each.value["ctl_event_trigger"]}${local.query_suffix}
  ${each.value["error_code"] != "" ? join("", [local.query_prefix, each.value["error_code"], local.query_suffix, ]) : ""}
  ${each.value["filename"] != "" ? join("", [local.query_file_prefix, each.value["filename"], local.query_suffix, ]) : ""}
                                    EOT
  operation                      = "GREATER_THAN_OR_EQUALS"
  notification_emails            = var.logzio_notification_emails
  search_timeframe_minutes       = each.value["search_timeframe_minutes"]
  value_aggregation_type         = "NONE"
  alert_notification_endpoints   = []
  suppress_notifications_minutes = 10
  is_enabled                     = each.value["is_enabled"]
  description                    = each.value["description"]
  severity_threshold_tiers {
    severity  = lookup({ P1 = "SEVERE", P2 = "HIGH", P3 = "MEDIUM", P4 = "LOW", P5 = "INFO" }, each.value["severity"])
    threshold = 1
  }
  tags = [
    module.facts.account_name_short,
  ]
}
```

**Comment by yyyogev** [comment]
Hi @sensedata1 ,
We are working on replacing the alerts resource with our new v2 alerts API which should resolve all the alert's related problems.

**Comment by janslow** [comment]
@yyyogev, do you know when the new v2 alerts API will be available?

It looks like an eventual consistency issue ([there's a `GET` request immediately after the `POST`](https://github.com/logzio/terraform-provider-logzio/blob/b489dd4a8b1bb3f2970a09a7531fff57fa19e6bc/logzio/resource_alert.go#L251)), because manually untainting the new `logzio_alert` resource (and running `terraform refresh`, if you don't refresh during plan/apply) solves the issue.

A relatively simple solution seems to be to use the data returned by [`client.CreateAlert`](https://github.com/logzio/terraform-provider-logzio/blob/b489dd4a8b1bb3f2970a09a7531fff57fa19e6bc/logzio/resource_alert.go#L234), rather than calling the API again. An alternative, simpler but hacky solution is to just add a delay after the alert is created.

I'd be happy to raise a PR for this if you'd consider accepting it?

**Comment by yyyogev** [comment]
We are working on it, should be aboit a week or so

**Comment by sensedata1** [comment]
Just checking in to see if there's been any movement on this? Thanks

**Comment by mirii1994** [comment]
@sensedata1 We've issued a PR (#69 ) which is currently under review :)

**Comment by sensedata1** [comment]
Great stuff! thanks :)

**Comment by mirii1994** [comment]
@sensedata1 v1.2.0 is out, and should handle this error.
Please let us know if you're having further issues with it :)

**Comment by sensedata1** [comment]
Fantastic, I'll be giving this a go in the next day or two. Thanks very much.

**Comment by Doron-Bargo** [comment]
Hi @sensedata1 - we would like to close this issue if it fixed for you
Kindly please update :) 
Thanks

**Comment by sensedata1** [comment]
@Doron-Bargo I'll be deploying another chunk of alerts in the next day or two for a new environment so I'll get to give it a decent workout then. I'll report back as soon as I've applied them. Thanks!

**Comment by sensedata1** [comment]
Just reporting back, that the latest provider does indeed work as intended, despite throwing >160 alerts at it in one apply. 
Awsome job folks, and much appreciated. I'd be completely stuffed without the provider so thanks again for the great work! :)
