### ISSUE TITLE
Opsgenie Endpoint Support

### ISSUE THREAD

**Issue by hackjoy** [logzio/terraform-provider-logzio#63]
Hi

As the web client supports Opsgenie - just wondering if there are plans to add it as a specific endpoint in terraform?

So it could be configured something like:

```terraform
resource "logzio_endpoint" "opsgenie" {
  title = "opsgenie"
  description = "Opsgenie Account"
  endpoint_type = "opsgenie"
  opsgenie {
    api_key = var.opsgenie_api_key
  }
}
```

**Comment by yyyogev** [comment]
Hi @hackjoy, thanks for the suggestion, it's on our road map with currently no ETA.
However, we are welcoming any contribution and suggestion that will benefit our clients if you are willing to take it on :)
LMN if you want to do it and needs any guidance

**Comment by mirii1994** [comment]
Hi @hackjoy,
We just release version 1.5.0, which adds support for OpsGenie! :)
You can see an example of how to use it here: https://github.com/logzio/terraform-provider-logzio/blob/master/examples/alert_endpoint/main.tf#L79
