### ISSUE TITLE
Support Archive settings

### ISSUE THREAD

**Issue by tianx2** [logzio/terraform-provider-logzio#64]
As a Logz.io administrator and terraform user, I would like to have a terraform resource from logz.io provider that would manage the archive settings for a given sub-account.

Since Logz.io has a REST API to do the operations, I imagine this should be pretty easy and straight-forward to implement.

**Comment by yyyogev** [comment]
Hi @tianx2 , thanks for the suggestion, it's on our backlog with currently no ETA.
However, we are welcoming any contribution and suggestion that will benefit our clients if you are willing to take it on :)
LMN if you want to do it and needs any guidance

**Comment by tianx2** [comment]
@yyyogev Just looking over how difficult it might be. It appears I need to make updates to `logzio/logzio_terraform_client` first before I can make the changes here. I would need to make a `client` to interact with the REST API for `archive`. Is this accurate?

**Comment by yyyogev** [comment]
That's right

**Comment by mirii1994** [comment]
Hi @tianx2 , for now i'm closing this issue because since v1.6 our provider supports the archive api.
Feel free to re-open or open a new issue if anything comes up.
