### ISSUE TITLE
Alert - Output Format configuration

### ISSUE THREAD

**Issue by Veluu** [logzio/terraform-provider-logzio#66]
Is it possible to configure alert's Output Format?

I don't see it in https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/alert anything which could help me to configure the following block:

![image](https://user-images.githubusercontent.com/16919963/114470565-1d70fb80-9bbd-11eb-98fd-4e118d4b1075.png)

**Comment by yyyogev** [comment]
Hi @Veluu 
These options are featured in our v2 alerts APIs. Currently, our Terraform provider supports only the v1 alerts. 
We are working on adding the v2 alerts to our provider, should be ready soon.
Have an awesome day!

**Comment by mirii1994** [comment]
@Veluu We added in the new version (v1.2.0) support for out v2 Alerts API, where you can use this feature.
Please let us know if you're having further issues :)
(#69)

**Comment by Veluu** [comment]
@mirii1994 can you provide an example of `logzio_alert_v2` with TABLE and two fields inside of it?

I used `logzio_alert_v2` resource but as soon as I switch from JSON to TABLE the provider crashes.

**Comment by mirii1994** [comment]
@Veluu  I've recreated the issue and working on a fix, sorry for the inconvenience

**Comment by mirii1994** [comment]
@Veluu We released v1.2.1 that fixes this bug.
The configuration that worked for me was:
```
resource "logzio_alert_v2" "my_alert" {
  title = "hello_there"
  notification_emails = ["test@test.com"]
  search_timeframe_minutes = 5
  is_enabled = false
  tags = ["some", "words"]
  suppress_notifications_minutes = 5
  output_type = "TABLE"
  sub_components {
    query_string = "loglevel:ERROR"
    should_query_on_all_accounts = true
    operation = "GREATER_THAN"
    value_aggregation_type = "COUNT"
    severity_threshold_tiers {
      severity = "HIGH"
      threshold = 10
    }
    severity_threshold_tiers {
      severity = "INFO"
      threshold = 5
    }
    columns {
      field_name = "test_field"
      regex = "[\\d]"
    }
  }
}
```

**Comment by Veluu** [comment]
> @Veluu We released v1.2.1 that fixes this bug.
> The configuration that worked for me was:
> 
> ```
> resource "logzio_alert_v2" "my_alert" {
>   title = "hello_there"
>   notification_emails = ["test@test.com"]
>   search_timeframe_minutes = 5
>   is_enabled = false
>   tags = ["some", "words"]
>   suppress_notifications_minutes = 5
>   output_type = "TABLE"
>   sub_components {
>     query_string = "loglevel:ERROR"
>     should_query_on_all_accounts = true
>     operation = "GREATER_THAN"
>     value_aggregation_type = "COUNT"
>     severity_threshold_tiers {
>       severity = "HIGH"
>       threshold = 10
>     }
>     severity_threshold_tiers {
>       severity = "INFO"
>       threshold = 5
>     }
>     columns {
>       field_name = "test_field"
>       regex = "[\\d]"
>     }
>   }
> }
> ```

According to https://registry.terraform.io/providers/logzio/logzio/latest/docs/resources/alert_v2 the `column` nested block should support `sort` attribute.

When I modified your example with:
```terraform
    columns {
      field_name = "test_field"
      regex      = "[\\d]"
      sort       = "DESC"
    }
```

It crashed.

I also managed to get error like:
```terraform

Error: resourceAlertCreate failed: sort must be one of [DESC DESC]

  on main.tf line 101, in resource "logzio_alert_v2" "my_alert_2":
 101: resource "logzio_alert_v2" "my_alert_2" {

```

**Comment by mirii1994** [comment]
@Veluu The source of this issue was in our client. We fixed the client and updated the provider to use the latest client version. Additionally, we've added test to prevent this kind of issue again.
v1.2.2 should now work fine.

Thank you for your feedback and patience :)

**Comment by Veluu** [comment]
@mirii1994 thank you. It's all good now.
