### ISSUE TITLE
Nested JSON items body_template in logzio_endpoint

### ISSUE THREAD

**Issue by Tenchi2xh** [logzio/terraform-provider-logzio#70]
Hi ! I would like to do the following:

```tf
resource "logzio_endpoint" "pagerduty" {
  title         = "..."
  description   = "..."
  endpoint_type = "custom"

  custom {
    url    = "https://..."
    method = "POST"

    headers = {
      "Authorization" = "..."
      "Content-type"  = "application/json"
    }

    body_template = {
      "foo" = "..."
      "bar" = {
        "baz" = "..."
        "b4r" = "..."
      }
    }
  }
}
```

Since many endpoints have APIs which require nested objects, I am attempting to do that by nesting maps in maps for `body_template`.

However, the type of `body_template` is hard set to `map of strings` which renders this task impossible (manually JSON-encoding the nested objects will result in a double encode with escaped characters):

```
Inappropriate value for attribute "body_template": element "bar": string
required.
```

Would it be possible to change the type to `string` and let the users wrap the whole map with a `jsonencode()`? That would enable users to use real world APIs and also as an added benefit allow for integer and float types.

Thanks for your time

**Comment by Tenchi2xh** [comment]
For now I will be forced to create some proxy that accepts a flattened version of the JSON object (where nested paths are represented with dots), unflattens it and proxies it to the destination API.

**Comment by mirii1994** [comment]
Hi @Tenchi2xh thanks for the feedback, we will check this issue and try to fix it.
However, currently we don't have ETA for this.
If you want, you are welcome to create your own PR to fix this issue, and we'll review it :)

**Comment by mirii1994** [comment]
@Tenchi2xh version 1.5.0 is out and should fix this issue.
You can see an example of how to use it here:
https://github.com/logzio/terraform-provider-logzio/blob/master/examples/alert_endpoint/main.tf#L30
Please let us know if this solves the issue :)

**Comment by mirii1994** [comment]
Hi @Tenchi2xh did v1.5.0 fix the issue for you?

**Comment by mirii1994** [comment]
@Tenchi2xh we're closing this issue, feel free to reopen if you have any further questions

**Comment by Tenchi2xh** [comment]
Hi sorry for the late reply :) Unfortunately I moved on from that project and cannot test this anymore, but I hope this will help somebody else!
