### ISSUE TITLE
Endpoint types in the documentation are incorrect

### ISSUE THREAD

**Issue by Tenchi2xh** [logzio/terraform-provider-logzio#71]
In `docs/resources/endpoint.md`, the endpoint types are documented as being written in snake case:

---
* `endpoint_type` - (Required) Specifies the endpoint resource type: `custom`, `slack`, `pager_duty`, `big_panda`, `data_dog`, `victorops`. Use the appropriate parameters for your selected endpoint type.
---

However, trying to use these for vendors will generate the following error message:

```
Error: value for endpoint type is unknown
```

Peeking at the source of the client https://github.com/logzio/logzio_terraform_client/blob/master/endpoints/client_endpoints.go#L36-L41 reveals that the strings expected are in one word:

```go
const (
    EndpointTypeSlack     endpointType = "slack"
    EndpointTypeCustom    endpointType = "custom"
    EndpointTypePagerDuty endpointType = "pagerduty"
    EndpointTypeBigPanda  endpointType = "bigpanda"
    EndpointTypeDataDog   endpointType = "datadog"
    EndpointTypeVictorOps endpointType = "victorops"
)
```

**Comment by mirii1994** [comment]
Hi @Tenchi2xh thank you for bringing it up to our attention! PR #72 fixed this mistake :)
