### ISSUE TITLE
specifying a match_phrase in filter_must

### ISSUE THREAD

**Issue by caphrim007** [logzio/terraform-provider-logzio#82]
I've been scratching my head on the correct syntax for this, and may be coming to the conclusion that its not possible given the current design of the provider, but what I'm looking to do is specify this value retrieved via the Logz API

```
"must": [
  {
    "match_phrase": {
      "kubernetes.container_name": {
        "query": "gremlin-logs"
      }
    }
  }
]
```

via terraform. When I attempt to send a map to the filter_must, it appears to want a string.

So far i've tried,

```
 30     filter_must = [
 31       {
 32         "kubernetes.container_name" = "gremlin-logs"
 33       }
 34     ]
```

```
 30     filter_must = [
 31       {
 32         "match_phrase" = "kubernetes.container_name = gremlin-logs"
 33       }
 34     ]
```

```
 30     filter_must = [
 31       {
 32        "match_phrase" = jsonencode({"kubernetes.container_name" = "gremlin-logs"})
 33       }
 34     ]
```

```
 30     filter_must = [
 31       {
 32         "match_phrase" = {
 33           "kubernetes.container_name" = "gremlin-logs"
 34         }
 35       }
 36     ]
```

and other combinations of maps and strings etc.

Is this possible?

**Comment by mirii1994** [comment]
Hi @caphrim007 , thank you for alerting us about this issue.
It seems that you're right, we'll look into this, and will release a fix soon!

**Comment by mirii1994** [comment]
@caphrim007 version 1.5.0 is out now and should fix your issue!
You can see an example of how to use it here: https://github.com/logzio/terraform-provider-logzio/blob/master/examples/alert_v2/main.tf#L31
Please let us know if this solves your issue :)

**Comment by mirii1994** [comment]
@caphrim007 Awesome! So i'm closing this issue for now. Feel free to reach out if you need :)
