### ISSUE TITLE
Import existing config for logzio_archive_logs cause a stacktrace

### ISSUE THREAD

**Issue by mcyrrer** [logzio/terraform-provider-logzio#93]
When I try to import existing settings from archive from a subaccount I get a nice stacktrace.

It is impossible to import existing config from logz.io and that prevents us to move to gitops these settings and rotate our client_secrets in an automated way.

logzio/logzio provider version 1.7.0

**Terraform config (values copied from the logz.io for the subaccount):**

provider "logzio" {
  alias     = "logzio_subaccountname"
  api_token = data.vault_generic_secret.logz_io_sys.data["api_token_terraform"]
  region    = "nl"
}

resource "logzio_archive_logs" "archive_logs_subaccountname" {
  provider = logzio.logzio_subaccountname
  storage_type = "BLOB"
  compressed = true
  enabled = true
  azure_blob_storage_settings { 
    tenant_id = "<tenat_id>"
    client_id = "<client_id>"
    client_secret = "<secret_id>"
    account_name = "<account_name>"
    container_name = "<container_name>"
 }
}

**Output from command**
terraform import logzio_archive_logs.archive_logs_subaccountname 123456
123456 copied from the account page on the subaccount.

logzio_archive_logs.archive_logs_galactica: Importing from ID "123456"...
logzio_archive_logs.archive_logs_galactica: Import prepared!
  Prepared logzio_archive_logs for import
logzio_archive_logs.archive_logs_galactica: Refreshing state... [id=123456]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-logzio_v1.7.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1977987]

goroutine 81 [running]:
github.com/logzio/logzio_terraform_provider/logzio.setArchive(0xc000334540, 0x0)
        github.com/logzio/logzio_terraform_provider/logzio/resource_archive_logs.go:296 +0x37
github.com/logzio/logzio_terraform_provider/logzio.resourceArchiveLogsRead(0xc000334540, 0x1ae1780, 0xc00000cd80, 0xc000334540, 0x0)
        github.com/logzio/logzio_terraform_provider/logzio/resource_archive_logs.go:189 +0xb5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000b7e80, 0xc0000b8550, 0x1ae1780, 0xc00000cd80, 0xc0000aa5f0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:455 +0x119
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000aa550, 0x1e26dc0, 0xc00007c8d0, 0xc0000b8280, 0xc0000aa550, 0xc00007c8d0, 0xc000612a48)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1b93de0, 0xc0000aa550, 0x1e26dc0, 0xc00007c8d0, 0xc0001027e0, 0x0, 0x1e26dc0, 0xc00007c8d0, 0xc0002da280, 0x12d)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000418000, 0x1e30d00, 0xc000782d80, 0xc0000b4300, 0xc00007c5d0, 0x2514b70, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc000418000, 0x1e30d00, 0xc000782d80, 0xc0000b4300, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000b01e0, 0xc000418000, 0x1e30d00, 0xc000782d80, 0xc0000b4300)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-logzio_v1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by mirii1994** [comment]
Hi @mcyrrer thanks for letting us know about this issue.
We will check this matter and will try to release a version with a fix :)

**Comment by mirii1994** [comment]
@mcyrrer I've managed to reproduce the error when I tried to import the archive with an ID that does not exist.
I've noticed that in your stacktrace the ID that's being imported is 123456. Is it the ID you tried to import with?

**Comment by mcyrrer** [comment]
Information should be kept secret ;) so I replaced my account id with 123456 through the issue description.

I my tf code I use  the real subaccount id on our subscription copied from the general setting page for the subaccount.


Terraform trace output (have anonymized it)
[
[debug2.log](https://github.com/logzio/terraform-provider-logzio/files/7504474/debug2.log)
](url)

**Comment by mirii1994** [comment]
Thanks for the clarification. I think I see what's the issue. From what I understand from your comment, when you're importing the archive, you're using your subaccount id
If you're trying to import an **archive**, then the ID that you need to use in the import command is the **archive id**, and not the sub account ID

**Comment by mcyrrer** [comment]
Thanks that solved it for me.

Solution(correct me if I am wrong):
You can not get archive id from the UI but you need to do a GET https://api-nl.logz.io/v2/archive/settings 
Then you get the archive id that later can be used in the terraform import command.

Thanks for the help!
