### ISSUE TITLE
Support grafana dashboards/objects

### ISSUE THREAD

**Issue by etiennejournet** [logzio/terraform-provider-logzio#95]
Hello,

The API definition for grafana objects is available, could the provider support it ? I'm interested in working on this if it can help, just tell me if you are interested.

Thanks,

**Comment by mirii1994** [comment]
Hi @etiennejournet !
Thank you for your interest to contribute!
The first PR should implement the import/export operations in the [client repo](https://github.com/logzio/logzio_terraform_client).
Then you can work on your PR for the provider :)
